osx_image: xcode9
language: objective-c
rvm:
- 2.4.1
podfile: Podfile
before_install:
- openssl aes-256-cbc -K $encrypted_894f337f9001_key -iv $encrypted_894f337f9001_iv
  -in APIKey.plist.enc -out Resources/APIKey.plist -d
- bundle install
- pod repo update
- pod install
script:
- set -o pipefail && xcodebuild test -workspace CCNumberValidator.xcworkspace -scheme
  CCNumberValidator -sdk iphonesimulator11.0 -destination 'name=iPhone SE,OS=11.0'
  -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty
- bundle exec danger
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'CCNumberValidator'
